- .github/workflows/ci.yml
- renovate.json
pre-commit configuration is not updated per default
> ci: update renovate configuration to support pre-commit

- .github/workflows/ci.yml
- renovate.json
Renovate configuration will be managed globally in https://github.com/SchweizerischeBundesbahnen/casc-renovate-preset-polarion-docker
> chore: renovate config is taken from preset

- .github/CODEOWNERS
it was missing the configuration CODEOWNERS
> fix: add CODEOWNERS

- app/WeasyprintController.py
Added support of pdf_variant parameter
> feat: support of pdf_variant parameter

- app/WeasyprintController.py
> fix: Fixed exception exposure into service response

- .github/workflows/ci.yml
- Dockerfile
- README.md
- app/WeasyprintController.py
Refs: #104
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> feat: info about the used weasyprint docker-image version

- app/WeasyprintController.py
Refs: #43
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).
> feat: More information about raised error

- Dockerfile
The correct maintainer details are reguired
> chore: update maintainer details

- requirements.txt
requirements.txt must define all version which will be automatically updated by Renovate
> ci: pin all versions in requirements.txt for Renovate

- Dockerfile
- app/SvgUtils.py
- entrypoint.sh
> fix: enable hardware acceleration using env variable

- app/SvgUtils.py
> fix: refactoring + error handling

- README.md
> docs: README.md updated

- Dockerfile
- README.md
- app/WeasyprintController.py
- entrypoint.sh
> chore: extend version endpoint with build timestamp and chromium version

- app/WeasyprintController.py
> fix: extend version endpoint with build timestamp and chromium version

- app/SvgUtils.py
trying to fix the reported bug
Refs: #78
> fix: better handling of SVG dimensions

- .config/container-structure-test.yaml
- .github/workflows/pr.yml
- Dockerfile
- README.md
Additionally: add container structure test
Due to the large number of vulnerabilities in the Debian base image, we need to minimise attack vectors and use different image  like Alpine
> fix: replace debian base image with alpine one

- entrypoint.sh
- poetry.lock
- pyproject.toml
- tests/test_container.py
- tox.ini
Fix entrypoint.sh and add a test for the docker container
> fix: fix alpine dbus problems

- entrypoint.sh
> fix: container restart does not work after migration to alpine

- entrypoint.sh
> fix: revert changes in entrypoint.sh due to DBus Debian config

- .github/workflows/pr.yml
- poetry.lock
- pyproject.toml
- tests/container/container-structure-test.yaml
security update using:
```
poetry update
```
> chore(deps): update h11 to v0.16.0 and httpcore to v1.0.9

- Dockerfile
- README.md
- docker-compose.yml
- tests/container/container-structure-test.yaml
> fix: use --init that provides enhanced security for Docker deployments

- Dockerfile
- README.md
- tests/test_container.py
> chore: remove unnecessary tools from docker image

- app/svg_utils.py
- tests/test_svg_utils.py
Refs: #152
'ex' units in SVG are supported now
> fix: support 'ex' units

- app/svg_utils.py
> 158 fix security hotspot

- .gitignore
- CONTRIBUTING.md
- poetry.lock
- pyproject.toml
- tox.ini
This pull request includes changes to improve documentation clarity, update dependencies, and enhance testing configurations. 
> chore(deps): update dependencies and improve project configuration

- poetry.lock
- pyproject.toml
This pull request updates the dependency version for `weasyprint` in the `pyproject.toml` file.
* [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L30-R30): Updated `weasyprint` from version `65.1` to `66.0` to ensure compatibility with the latest features and fixes.
> feat(deps): update dependency weasyprint to v66

- app/weasyprint_controller.py
Refs: #193
add custom_metadata query parameter
> feat: support custom metadata in PDF conversion

- app/svg_processor.py
- tests/test-data/svg-image-without-xmlns.html
- tests/test_container.py
- tests/test_svg_processor.py
- tests/utils_pdf.py
This pull request improves SVG processing robustness and modernizes the test suite for PDF/SVG conversion. The main changes ensure SVGs without an XML namespace are handled gracefully, refactor test utilities for maintainability, and introduce new test cases for edge scenarios.
> fix: ensure `xmlns` and `xmlns:xlink` attributes are set for proper SVG rendering

- README.md
- entrypoint.sh
Refs: #207
User must have ability to add additional fonts.
> feat: ability to add additional fonts
